version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres-test
    ports:
      - "5432:5432"
    enviroment:
      POSTGRES_DB: data
      POSTGRES_USSER: postgres
      POSTGRES_PASSWORD: postgres.
    volumes: pgdata:/data/postgres

volumes:
  pgdata:
    driver: local